### PR TITLE
[WIP - Feat-#1] Adding sign up to mailing list

### PR DESCRIPTION
**Pull request by tanyapowell**

### CODE REVIEW

**Comment by tanyapowell** [comment]
[Add Sign up to mailing list form to the Coming Soon Page](https://trello.com/c/xUeXheYT/3-add-sign-up-to-mailing-list-form-to-the-coming-soon-page)

**Comment by tanyapowell** [comment]
Haven't finished it yet, just opened the PR so I could run the CI tool and check I hadn't broken anything so far haha.

Will finish it in the morning 😊




---- On Sat, 17 Nov 2018 14:06:10 -0800 notifications@github.com wrote ----



@dionnecf approved this pull request.

Not sure how you view these changes on website to see what it looks like before approval.

I guess I just need to clone and build locally, but I haven't got time this weekend, so I am just going to trust you :-). The code looks neat though.

Thanks for doing this.

**Comment by dionnecf** [comment]
> Haven't finished it yet, just opened the PR so I could run the CI tool and check I hadn't broken anything so far haha. Will finish it in the morning 😊
> […](#)
> ---- On Sat, 17 Nov 2018 14:06:10 -0800 notifications@github.com wrote ---- @dionnecf approved this pull request. Not sure how you view these changes on website to see what it looks like before approval. I guess I just need to clone and build locally, but I haven't got time this weekend, so I am just going to trust you :-). The code looks neat though. Thanks for doing this. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
I take it I shouldn't press merge pull request then if you're not finished? lol


> Haven't finished it yet, just opened the PR so I could run the CI tool and check I hadn't broken anything so far haha. Will finish it in the morning 😊
> […](#)
> ---- On Sat, 17 Nov 2018 14:06:10 -0800 notifications@github.com wrote ---- @dionnecf approved this pull request. Not sure how you view these changes on website to see what it looks like before approval. I guess I just need to clone and build locally, but I haven't got time this weekend, so I am just going to trust you :-). The code looks neat though. Thanks for doing this. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by dionnecf** [comment]
> Haven't finished it yet, just opened the PR so I could run the CI tool and check I hadn't broken anything so far haha. Will finish it in the morning 😊
> […](#)

I take it I shouldn't press merge pull request then if you're not finished? lol

**Comment by dionnecf** [comment]
Merging changes into master

**Pull request merged**
